spring.application.name=asap-backend
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.default-property-inclusion=non_null
server.error.include-message=never
server.error.include-stacktrace=never
